h,m=map(int,input().split(":"))
a=abs(h*30-(11*m)/2.0)
if(a<360-a):
    if(a>int(a)):
        print(a)
    else:
        print(a)
else:
    if((360-a)>(int)(360-a)):
        print(360-a)
    else:
        print(360-a)